//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int FacturaID { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> FormaPago { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> Baja { get; set; }
    
        public virtual Pedido Pedido { get; set; }
    }
}
